data_file_path = "/Users/Lerberber/Desktop/Bhat/SuperGans/data/Epilepsy_preprocessed.h5"
classifier_path = "/Users/Lerberber/Desktop/Bhat/SuperGans/CNN1_scripts/Datasets/Epilepsy_1DCNN_extended.ckpt"
class_label = 3
write_train_results = true
